// AUTO-GENERATED by scripts/xlsx-to-content.ts — do not edit by hand.
// Source: "Edgeloop Projects (1).xlsx" + content/manifest.json (extract-base64.ts).
// Regenerate: node_modules/.bin/tsx scripts/extract-base64.ts && node_modules/.bin/tsx scripts/xlsx-to-content.ts

import type { SiteContent } from './schema'

export const site: SiteContent = {
  "about": "edgeloop is a creative studio based on one belief: the right visual changes how people think, feel, and decide. we create artist visuals, brand content, dj set productions, and anamorphic experiences for companies. every project starts with intention and ends with something that could only come from us. no templates, no shortcuts. each piece is built from scratch, shaped by the specific energy of the project, the artist, or the brand we are working with. over the years we have contributed to live performances, launch events, marketing campaigns, and large-scale digital experiences. we believe powerful visuals do more than look good. they shift perception and stay with people long after the screen goes dark.",
  "estd": 2023,
  "contact": {
    "phone": "+91 - 8210552902",
    "email": "edgeloop9@gmail.com"
  },
  "behanceUrl": "https://www.behance.net/gallery/238866345/Edgeloop-2025-Portfolio",
  "categories": [
    {
      "id": "anamorphics",
      "label": "Anamorphics",
      "projects": [
        {
          "slug": "nsm-launch-event",
          "name": "NSM Launch Event",
          "category": "anamorphics",
          "order": 0,
          "layout": "stack",
          "images": [
            {
              "src": "/media/anamorphics/nsm-launch-event/0.png",
              "alt": "NSM Launch Event — Anamorphics (1)",
              "width": 1083,
              "height": 290,
              "transparent": true
            },
            {
              "src": "/media/anamorphics/nsm-launch-event/1.png",
              "alt": "NSM Launch Event — Anamorphics (2)",
              "width": 1059,
              "height": 289,
              "transparent": true
            },
            {
              "src": "/media/anamorphics/nsm-launch-event/2.png",
              "alt": "NSM Launch Event — Anamorphics (3)",
              "width": 1068,
              "height": 261,
              "transparent": true
            }
          ],
          "video": {
            "provider": "youtube",
            "youtubeUrl": "https://youtu.be/GVCPGDDjrT8"
          },
          "stats": "500 attendees, 3 min, 150ft screen size",
          "description": "3D anamorphic film for Novo Nordisk's national sales meeting, tracing the brand's insulin heritage from 1960 through to the Insuject-X pen. Built for a large-format LED stage and played to around 900 sales and medical staff over a 3-day meet."
        },
        {
          "slug": "excon-billboard",
          "name": "Excon Billboard",
          "category": "anamorphics",
          "order": 1,
          "layout": "grid2x2",
          "images": [
            {
              "src": "/media/anamorphics/excon-billboard/0.png",
              "alt": "Excon Billboard — Anamorphics (1)",
              "width": 929,
              "height": 500,
              "transparent": true
            },
            {
              "src": "/media/anamorphics/excon-billboard/1.png",
              "alt": "Excon Billboard — Anamorphics (2)",
              "width": 930,
              "height": 500,
              "transparent": true
            },
            {
              "src": "/media/anamorphics/excon-billboard/2.png",
              "alt": "Excon Billboard — Anamorphics (3)",
              "width": 929,
              "height": 500,
              "transparent": true
            },
            {
              "src": "/media/anamorphics/excon-billboard/3.png",
              "alt": "Excon Billboard — Anamorphics (4)",
              "width": 929,
              "height": 500,
              "transparent": true
            }
          ],
          "video": {
            "provider": "youtube",
            "youtubeUrl": "https://youtu.be/WHYfl3bUl2k"
          },
          "stats": "70k+ footfall, +40% booth dwell time, 12 days concept to delivery",
          "description": "Title reveal for CII EXCON 2023, billed as 'The Largest Ever' edition of South Asia's premier construction equipment expo. Staged as a 3D anamorphic piece on the venue's main LED, seen by a footfall of around 70,000 visitors over 5 days."
        },
        {
          "slug": "aditya-birla-analyst-day",
          "name": "Aditya Birla",
          "category": "anamorphics",
          "order": 2,
          "layout": "grid2x2",
          "images": [
            {
              "src": "/media/anamorphics/aditya-birla-analyst-day/0.png",
              "alt": "Aditya Birla Analyst Day — Anamorphics (1)",
              "width": 1000,
              "height": 594,
              "transparent": true
            },
            {
              "src": "/media/anamorphics/aditya-birla-analyst-day/1.png",
              "alt": "Aditya Birla Analyst Day — Anamorphics (2)",
              "width": 1000,
              "height": 594,
              "transparent": true
            },
            {
              "src": "/media/anamorphics/aditya-birla-analyst-day/2.png",
              "alt": "Aditya Birla Analyst Day — Anamorphics (3)",
              "width": 1000,
              "height": 594,
              "transparent": true
            },
            {
              "src": "/media/anamorphics/aditya-birla-analyst-day/3.png",
              "alt": "Aditya Birla Analyst Day — Anamorphics (4)",
              "width": 1000,
              "height": 594,
              "transparent": true
            }
          ],
          "video": {
            "provider": "youtube",
            "youtubeUrl": "https://youtu.be/mvm3cd_uAQE"
          },
          "stats": "1wk concept to delivery, 3x more attendees interaction, +60% engagement",
          "description": "Pan-India anamorphic visual for Aditya Birla Capital, framing the brand across glowing maps of the country. Produced for the company's annual leadership conclave and presented to around 500 guests."
        },
        {
          "slug": "tata-accelerating-india",
          "name": "Tata AI",
          "category": "anamorphics",
          "order": 3,
          "layout": "stack",
          "images": [
            {
              "src": "/media/anamorphics/tata-accelerating-india/0.jpg",
              "alt": "TATA Accelerating India — Anamorphics (1)",
              "width": 1300,
              "height": 433,
              "transparent": false
            },
            {
              "src": "/media/anamorphics/tata-accelerating-india/1.jpg",
              "alt": "TATA Accelerating India — Anamorphics (2)",
              "width": 1300,
              "height": 433,
              "transparent": false
            },
            {
              "src": "/media/anamorphics/tata-accelerating-india/2.jpg",
              "alt": "TATA Accelerating India — Anamorphics (3)",
              "width": 1300,
              "height": 433,
              "transparent": false
            }
          ],
          "video": {
            "provider": "youtube",
            "youtubeUrl": "https://youtu.be/q1WdCPqAUEs"
          },
          "stats": "2wks concept to delivery , 4x more attendees, +40% booth walk-ins",
          "description": "Anamorphic opener for the Tata AI Summit, uniting Tata group brands — Tata Motors, Tata Electronics, Tata Power, TCS, Air India, Tata Communications, Tata Steel and Tata MD — across an immersive data-rain mega-screen. Screened to roughly 1,200 delegates across the summit."
        },
        {
          "slug": "hdfc-annual-sparsh",
          "name": "HDFC Annual Sparsh",
          "category": "anamorphics",
          "order": 4,
          "layout": "stack",
          "images": [
            {
              "src": "/media/anamorphics/hdfc-annual-sparsh/0.png",
              "alt": "HDFC Annual Sparsh — Anamorphics (1)",
              "width": 739,
              "height": 262,
              "transparent": true
            },
            {
              "src": "/media/anamorphics/hdfc-annual-sparsh/1.png",
              "alt": "HDFC Annual Sparsh — Anamorphics (2)",
              "width": 739,
              "height": 262,
              "transparent": true
            },
            {
              "src": "/media/anamorphics/hdfc-annual-sparsh/2.png",
              "alt": "HDFC Annual Sparsh — Anamorphics (3)",
              "width": 739,
              "height": 262,
              "transparent": true
            }
          ],
          "video": {
            "provider": "youtube",
            "youtubeUrl": "https://youtu.be/p8f5cLGVZIM"
          },
          "stats": "2wks concept to delivery, 800+ attendees, 4 mins content",
          "description": "Anamorphic stage content for HDFC Life's Annual Sparsh 2024, carrying the brand's signature growth-arrow motif. Created for the annual flagship event and shown to about 800 attendees."
        },
        {
          "slug": "mindgate",
          "name": "Mindgate",
          "category": "anamorphics",
          "order": 5,
          "layout": "grid2x2",
          "images": [
            {
              "src": "/media/anamorphics/mindgate/0.png",
              "alt": "Mindgate — Anamorphics (1)",
              "width": 449,
              "height": 389,
              "transparent": true
            },
            {
              "src": "/media/anamorphics/mindgate/1.png",
              "alt": "Mindgate — Anamorphics (2)",
              "width": 449,
              "height": 389,
              "transparent": true
            },
            {
              "src": "/media/anamorphics/mindgate/2.png",
              "alt": "Mindgate — Anamorphics (3)",
              "width": 448,
              "height": 388,
              "transparent": true
            },
            {
              "src": "/media/anamorphics/mindgate/3.png",
              "alt": "Mindgate — Anamorphics (4)",
              "width": 449,
              "height": 389,
              "transparent": true
            }
          ],
          "video": {
            "provider": "youtube",
            "youtubeUrl": "https://youtu.be/K4w7d2_lDkY"
          },
          "stats": "50k+ footfall, +30% booth dwell time, 10 days concept to delivery",
          "description": "Anamorphic brand reveal for Mindgate — 'Delivering Innovation' — staged inside a clean light-box environment. Produced for a fintech industry summit with around 400 attendees."
        },
        {
          "slug": "all-you-can-street",
          "name": "All You Can Street",
          "category": "anamorphics",
          "order": 6,
          "layout": "single",
          "images": [],
          "video": {
            "provider": "youtube",
            "youtubeUrl": "https://youtu.be/J37BD1LWV9s"
          },
          "description": "An anamorphic 3D concert experience for All You Can Street — as the lights rise over a packed crowd, a full truss-and-lighting rig, and a glowing LED stage, a cast of playful characters comes to life. Crafted as mind-bending, forced-perspective 3D and rendered in 4K, every frame is built to break out of the screen and drop you straight into the front row, capturing the pure energy of the event before the doors even open."
        },
        {
          "slug": "yes-bank-ncr1",
          "name": "Yes Bank NCR1",
          "category": "anamorphics",
          "order": 7,
          "layout": "single",
          "images": [],
          "video": {
            "provider": "youtube",
            "youtubeUrl": "https://youtu.be/i_b1WJ1LXlo"
          },
          "description": "An anamorphic 3D film for YesBank — NCR1: a premium, forced-perspective experience that turns a milestone into a moment. Set inside a sculpted black-and-gold display that appears to break out of the screen, it builds from cinematic 3D detail to a jewel-set golden crown and a burst of celebration, before resolving on the NCR1 mark and its promise — Power. Resilience. Success. Crafted as mind-bending anamorphic 3D and rendered in 4K, every frame is designed to make being number one feel monumental."
        },
        {
          "slug": "motorola-razr-anamorphic-launch",
          "name": "Motorola Razor",
          "category": "anamorphics",
          "order": 8,
          "layout": "single",
          "images": [],
          "video": {
            "provider": "youtube",
            "youtubeUrl": "https://youtu.be/6PLwDzdVQC8"
          },
          "description": "An anamorphic 3D launch film for the Motorola Razr — the iconic flip phone brought to life in mind-bending, forced-perspective 3D that breaks out of the screen and into real space. Rendered in 4K, every frame is built around the device's signature flip and sleek silhouette, turning a product reveal into a head-turning anamorphic moment designed to stop people mid-scroll and mid-street."
        },
        {
          "slug": "tata-steel-dureco",
          "name": "Tata Steel Dureco",
          "category": "anamorphics",
          "order": 9,
          "layout": "single",
          "images": [],
          "video": {
            "provider": "youtube",
            "youtubeUrl": "https://youtu.be/Nttegvgrj3c"
          },
          "description": "An anamorphic 3D launch film for Tata Steel — #TATADURECO, marking the arrival of its GGBS (Ground Granulated Blast-furnace Slag): a stronger, greener future for construction. Built as mind-bending, forced-perspective 3D that appears to break out of the screen and into real space, every frame turns the unveiling of a sustainable building material into a head-turning anamorphic spectacle — engineered to make the launch feel as monumental as the brand behind it."
        },
        {
          "slug": "ayc-offthegrid",
          "name": "AYC OffTheGrid",
          "category": "anamorphics",
          "order": 10,
          "layout": "single",
          "images": [],
          "video": {
            "provider": "youtube",
            "youtubeUrl": "https://youtu.be/U1ewmEYsNz0"
          },
          "description": "An anamorphic 3D film for All You Can: Off The Grid — a high-voltage, forced-perspective billboard that bends a neon-lit world out of the screen and into the street. Racing through an electric blue-and-purple LED tunnel, it teases everything the event brings — the craziest workshops, the coolest brands, music and pure street culture — before landing on the call to action: Time To Go Street, 28 Feb–2 Mar. Built as mind-bending anamorphic 3D, every frame is designed to stop people mid-street and pull them straight into the experience."
        }
      ]
    },
    {
      "id": "artists",
      "label": "Artists",
      "projects": [
        {
          "slug": "aminjaz",
          "name": "Aminjaz",
          "category": "artists",
          "order": 0,
          "layout": "trio",
          "images": [
            {
              "src": "/media/artists/aminjaz/0.jpg",
              "alt": "Aminjaz — Artists (1)",
              "width": 1280,
              "height": 1280,
              "transparent": false
            },
            {
              "src": "/media/artists/aminjaz/1.jpg",
              "alt": "Aminjaz — Artists (2)",
              "width": 1280,
              "height": 720,
              "transparent": false
            },
            {
              "src": "/media/artists/aminjaz/2.jpg",
              "alt": "Aminjaz — Artists (3)",
              "width": 1280,
              "height": 1280,
              "transparent": false
            }
          ],
          "description": "A set of CGI motion frames produced under the Aminjaz banner — a hero prop study, a playful whack-a-DJ concept, and a neon arcade machine. Three distinct ideas tied together by bold lighting and clean render craft."
        },
        {
          "slug": "stuvi",
          "name": "Stuvi",
          "category": "artists",
          "order": 1,
          "layout": "single",
          "images": [],
          "description": "CGI motion and visual content produced for Stuvi."
        },
        {
          "slug": "kimera",
          "name": "Kimera",
          "category": "artists",
          "order": 2,
          "layout": "single",
          "images": [],
          "description": "CGI motion and visual content produced for Kimera."
        },
        {
          "slug": "the-sincerities",
          "name": "The Sincerities",
          "category": "artists",
          "order": 3,
          "layout": "duo",
          "images": [
            {
              "src": "/media/artists/the-sincerities/0.jpg",
              "alt": "The Sincerities — Artists (1)",
              "width": 1280,
              "height": 720,
              "transparent": false
            },
            {
              "src": "/media/artists/the-sincerities/1.jpg",
              "alt": "The Sincerities — Artists (2)",
              "width": 1280,
              "height": 720,
              "transparent": false
            }
          ],
          "description": "Two CGI motion pieces for The Sincerities — a moonlit beach-house drive and a bold yellow colour study. Atmospheric, cinematic visuals built to set a mood."
        }
      ]
    },
    {
      "id": "brands",
      "label": "Brands",
      "projects": [
        {
          "slug": "fila",
          "name": "Fila",
          "category": "brands",
          "order": 0,
          "layout": "single",
          "images": [
            {
              "src": "/media/brands/fila/0.jpg",
              "alt": "Fila — Brands",
              "width": 474,
              "height": 836,
              "transparent": false
            }
          ],
          "stats": "8hrs concept to delivery, 100k+ views, 0 vehicles used",
          "description": "Custom 3D brand posts for FILA hyper-real truck wraps and branded livery rendered entirely in 3D. Every angle. every reflection, every surface built without a single vehicle on set or location day spent."
        },
        {
          "slug": "ace-blends",
          "name": "Ace Blends",
          "category": "brands",
          "order": 1,
          "layout": "single",
          "images": [
            {
              "src": "/media/brands/ace-blends/0.jpg",
              "alt": "Ace Blends — Brands",
              "width": 577,
              "height": 1024,
              "transparent": false
            }
          ],
          "video": {
            "provider": "youtube",
            "youtubeUrl": "https://youtube.com/shorts/6JAFbFiuSx8"
          },
          "stats": "11hrs concept to delivery, 70k+ views, 0 products used",
          "description": "Custom 3D brand posts for Ace Blends product packaging rendered in a hyper-real Industrial environment. Every surface, every reflection, every detail built entirely in 3D without a single product on set."
        },
        {
          "slug": "footlocker",
          "name": "Footlocker",
          "category": "brands",
          "order": 2,
          "layout": "single",
          "images": [
            {
              "src": "/media/brands/footlocker/0.jpg",
              "alt": "Footlocker — Brands",
              "width": 588,
              "height": 1077,
              "transparent": false
            }
          ],
          "video": {
            "provider": "youtube",
            "youtubeUrl": "https://youtube.com/shorts/9Z6-65uO1wE"
          },
          "stats": "10hrs concept to delivery, 100k+ views, 4 final hero shots",
          "description": "Foot Locker needed a campaign visual that felt 1ike a crime scene. We built a full nocturnal 3D environment wet asphalt, police lights, dramatic shadows and placed the product inside it. No studio. No shoot. Just pure 3D world-building around the brief."
        },
        {
          "slug": "crocs",
          "name": "Crocs",
          "category": "brands",
          "order": 3,
          "layout": "single",
          "images": [
            {
              "src": "/media/brands/crocs/0.jpg",
              "alt": "Crocs — Brands",
              "width": 591,
              "height": 1077,
              "transparent": false
            }
          ],
          "video": {
            "provider": "youtube",
            "youtubeUrl": "https://youtube.com/shorts/8kP9vhL1QcE"
          },
          "stats": "12hrs concept to delivery, 80k+ views, 4 final hero shots",
          "description": "Crocs asked for something unexpected. We dropped the product into a sweeping golden-hour mountain landscape - rain falling, flowers in bloom, sky on fire. The brief was monsoon season. We built the whole world around it."
        },
        {
          "slug": "paapi",
          "name": "Paapi",
          "category": "brands",
          "order": 4,
          "layout": "single",
          "images": [
            {
              "src": "/media/brands/paapi/0.jpg",
              "alt": "Paapi — Brands",
              "width": 598,
              "height": 1079,
              "transparent": false
            }
          ],
          "video": {
            "provider": "youtube",
            "youtubeUrl": "https://youtube.com/shorts/BX-FC79ayUc"
          },
          "stats": "12hrs concept to delivery, 100k+ views, 0 set days",
          "description": "The brief was simple make it feel like a night you'd never forget. We built a full tropical sunset environment from scratch palm silhouettes, string lights, open ocean, a pirate ship on the horizon. The product just lived inside the world we created."
        }
      ]
    },
    {
      "id": "djsets",
      "label": "DJ Sets",
      "projects": [
        {
          "slug": "kitty-party-karan-kanchan",
          "name": "Kitty Party - Karan Kanchan",
          "category": "djsets",
          "order": 0,
          "layout": "grid2x2",
          "images": [
            {
              "src": "/media/djsets/kitty-party-karan-kanchan/0.jpg",
              "alt": "Kitty Party - Karan Kanchan — DJ Sets (1)",
              "width": 1280,
              "height": 720,
              "transparent": false
            },
            {
              "src": "/media/djsets/kitty-party-karan-kanchan/1.jpg",
              "alt": "Kitty Party - Karan Kanchan — DJ Sets (2)",
              "width": 1280,
              "height": 720,
              "transparent": false
            },
            {
              "src": "/media/djsets/kitty-party-karan-kanchan/2.jpg",
              "alt": "Kitty Party - Karan Kanchan — DJ Sets (3)",
              "width": 1280,
              "height": 720,
              "transparent": false
            },
            {
              "src": "/media/djsets/kitty-party-karan-kanchan/3.jpg",
              "alt": "Kitty Party - Karan Kanchan — DJ Sets (4)",
              "width": 1280,
              "height": 720,
              "transparent": false
            }
          ],
          "description": "Set visuals and live coverage for Karan Kanchan's 'Kitty Party' show, drenched in signature pink-and-blue stage light. Shot largely from behind the decks, the frames capture both the artist in flow and the crowd going off in front of him. A bold, high-energy gallery built to carry the party's identity online."
        },
        {
          "slug": "nucleya-x-stuvi-x-aminjaz",
          "name": "Nucleya x Stuvi x Aminjaz",
          "category": "djsets",
          "order": 1,
          "layout": "single",
          "images": []
        },
        {
          "slug": "halloween-dev-raiyani",
          "name": "Halloween - Dev Raiyani",
          "category": "djsets",
          "order": 2,
          "layout": "grid2x2",
          "images": [
            {
              "src": "/media/djsets/halloween-dev-raiyani/0.jpg",
              "alt": "Halloween - Dev Raiyani — DJ Sets (1)",
              "width": 1280,
              "height": 720,
              "transparent": false
            },
            {
              "src": "/media/djsets/halloween-dev-raiyani/1.jpg",
              "alt": "Halloween - Dev Raiyani — DJ Sets (2)",
              "width": 1280,
              "height": 720,
              "transparent": false
            },
            {
              "src": "/media/djsets/halloween-dev-raiyani/2.jpg",
              "alt": "Halloween - Dev Raiyani — DJ Sets (3)",
              "width": 1280,
              "height": 720,
              "transparent": false
            },
            {
              "src": "/media/djsets/halloween-dev-raiyani/3.jpg",
              "alt": "Halloween - Dev Raiyani — DJ Sets (4)",
              "width": 1280,
              "height": 720,
              "transparent": false
            }
          ],
          "description": "Event coverage for antiSOCIAL's Halloween Bash, a packed warehouse strung with cobwebs and ghouls under eerie red and green light. The photography captures the haunted-house production design and the costumed crowd in full swing. Moody, atmospheric frames that bottle the chaos of the night."
        },
        {
          "slug": "khar-social-stuvi",
          "name": "Khar Social - Stuvi",
          "category": "djsets",
          "order": 3,
          "layout": "single",
          "images": []
        },
        {
          "slug": "notice-dev-raiyani",
          "name": "Notice - Dev Raiyani",
          "category": "djsets",
          "order": 4,
          "layout": "single",
          "images": []
        },
        {
          "slug": "rayas-roof-ep-1-ria-palkar",
          "name": "Rayas Roof EP 1 - Ria Palkar",
          "category": "djsets",
          "order": 5,
          "layout": "single",
          "images": []
        },
        {
          "slug": "rayas-roof-ep-2-ria-palkar",
          "name": "Rayas Roof EP 2 - Ria Palkar",
          "category": "djsets",
          "order": 6,
          "layout": "single",
          "images": []
        },
        {
          "slug": "rayas-roof-ep-3-ria-palkar",
          "name": "Rayas Roof EP 3 - Ria Palkar",
          "category": "djsets",
          "order": 7,
          "layout": "single",
          "images": []
        },
        {
          "slug": "rayas-roof-ep-4-ria-palkar",
          "name": "Rayas Roof EP 4 - Ria Palkar",
          "category": "djsets",
          "order": 8,
          "layout": "single",
          "images": []
        }
      ]
    }
  ]
} satisfies SiteContent

export default site
